// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCeZb4L-J7z1RbrWDFQcqp16ptJERvM_fw',
    appId: '1:128143577433:web:0ac7165db7d7ee37677c48',
    messagingSenderId: '128143577433',
    projectId: 'campus-trade-app',
    authDomain: 'campus-trade-app.firebaseapp.com',
    storageBucket: 'campus-trade-app.firebasestorage.app',
    measurementId: 'G-44ZQFZJXNN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDD5s1nyAr5R9DD_ZUJXwvNethUHe8zWKo',
    appId: '1:128143577433:android:57ba5f58e17d9513677c48',
    messagingSenderId: '128143577433',
    projectId: 'campus-trade-app',
    storageBucket: 'campus-trade-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCCO0qVCG-XkCz11ZaKW0mvxImtvufl4MY',
    appId: '1:128143577433:ios:358f147de14cc2f0677c48',
    messagingSenderId: '128143577433',
    projectId: 'campus-trade-app',
    storageBucket: 'campus-trade-app.firebasestorage.app',
    iosClientId: '128143577433-ir5i5o5pmc98vn1o693i7c45oaimucos.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCCO0qVCG-XkCz11ZaKW0mvxImtvufl4MY',
    appId: '1:128143577433:ios:358f147de14cc2f0677c48',
    messagingSenderId: '128143577433',
    projectId: 'campus-trade-app',
    storageBucket: 'campus-trade-app.firebasestorage.app',
    iosClientId: '128143577433-ir5i5o5pmc98vn1o693i7c45oaimucos.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCeZb4L-J7z1RbrWDFQcqp16ptJERvM_fw',
    appId: '1:128143577433:web:e00258e958e24e6c677c48',
    messagingSenderId: '128143577433',
    projectId: 'campus-trade-app',
    authDomain: 'campus-trade-app.firebaseapp.com',
    storageBucket: 'campus-trade-app.firebasestorage.app',
    measurementId: 'G-MPLE6K5H0Q',
  );
}
